import { Entity } from '../Entity';
import { CorsetMeasurement } from '@common/interfaces/product-order/Corset-measurement';
import { CorsetStatus } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/corset-status.enum';
import { ProductOperationStatus } from '@common/enums/product-operation-status';
import { OrderTerm } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/order-term.enum';
import { ProductOrderResponse } from './Product-order-response';

export interface CorsetOrderResponse extends ProductOrderResponse {
  statusComplete: boolean;
  afterBlockCorsetPlasticThickness: boolean;
  blockingExecutor1: Entity;
  blockingExecutor2: Entity;
  blockingStatus: ProductOperationStatus;
  color: string;
  carcassStatus: ProductOperationStatus;
  carcassExecutor1: Entity;
  carcassExecutor2: Entity;
  competentCutting: boolean;
  corsetFastenersInstallation: boolean;
  corsetMeasurement: CorsetMeasurement;
  corsetProblocking: boolean;
  corsetStatus: CorsetStatus;
  corsetType: Entity;
  cuttingExecutor1: Entity;
  cuttingExecutor2: Entity;
  cuttingStatus: ProductOperationStatus;
  deformationInsideCorsetLiner: boolean;
  fastenersInstallExecutor1: Entity;
  fastenersInstallExecutor2: Entity;
  fastenersInstallStatus: ProductOperationStatus;
  levelOfAxillaryPelot: boolean;
  otherDefects: string;
  paintQualityAfterBlocking: boolean;
  plasticBend: boolean;
  plasticType: Entity;
  productReadinessAtTime: boolean;
  productionTime: OrderTerm;
  purityBeforeLoadingInThermostol: boolean;
  sameColorFrames: boolean;
  seamPolishing: boolean;
  stonesAfterTights: boolean;
  surfaceScratches: boolean;
  turningExecutor1: Entity;
  turningExecutor2: Entity;
  turningQuality: boolean;
  turningStatus: ProductOperationStatus;
  whriteWhoInstalledFasteners: boolean;
  whriteWhoTurned: boolean;
  guaranty?: string;
  purchaseDeviceId?: string;
}
