import { CorsetMeasurement } from './Corset-measurement';
import { ProductOperationStatus } from '@common/enums/product-operation-status';
import { OrderTerm } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/order-term.enum';
import { CorsetStatus } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/corset-status.enum';
import { ProductOrderUpdate } from './Product-order-update';
import { Entity } from '@common/interfaces/Entity';

export interface CorsetOrderUpdate extends ProductOrderUpdate {
  corsetMeasurement: CorsetMeasurement;
  corsetTypeId: string;
  plasticTypeId: string;
  color: string;
  carcassExecutor1Id: Entity;
  carcassExecutor2Id: Entity;
  carcassStatus: ProductOperationStatus;
  afterBlockCorsetPlasticThickness: boolean;
  blockingExecutor1Id: string;
  blockingExecutor2Id: string;
  blockingStatus: ProductOperationStatus;
  competentCutting: boolean;
  corsetFastenersInstallation: boolean;
  corsetProblocking: boolean;
  corsetStatus: CorsetStatus;
  cuttingExecutor1Id: string;
  cuttingExecutor2Id: string;
  cuttingStatus: ProductOperationStatus;
  deformationInsideCorsetLiner: boolean;
  fastenersInstallExecutor1Id: string;
  fastenersInstallExecutor2Id: string;
  fastenersInstallStatus: ProductOperationStatus;
  is3DModelReady: boolean;
  levelOfAxillaryPelot: boolean;
  otherDefects: string;
  paintQualityAfterBlocking: boolean;
  plasticBend: boolean;
  productReadinessAtTime: boolean;
  productionTime: OrderTerm;
  purityBeforeLoadingInThermostol: boolean;
  sameColorFrames: boolean;
  seamPolishing: boolean;
  statusComplete: boolean;
  stonesAfterTights: boolean;
  surfaceScratches: boolean;
  turningExecutor1Id: string;
  turningExecutor2Id: string;
  turningQuality: boolean;
  turningStatus: ProductOperationStatus;
  whriteWhoInstalledFasteners: boolean;
  whriteWhoTurned: boolean;
}
