import { CorsetOperationStatus } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/corser-operation-status.enum';
import { OrderTerm } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/order-term.enum';
import { CorsetStatus } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/corset-status.enum';
import { ProductStatus } from '@modules/patients/patient/patient-visits/visit-meansurements/corset-order/models/product-status.enum';
import { CorsetMeasurement } from '@common/interfaces/product-order/Corset-measurement';

export interface CorsetOrderUpdate {
  corsetMeasurement: CorsetMeasurement;
  dateOfIssue: string;
  corsetTypeId: string;
  plasticTypeId: string;
  color: string;
  dateOfIssueTurner: string;
  dateSendingToBranch: string;
  branchId: string;
  name: string;
  afterBlockCorsetPlasticThickness: boolean;
  blockingExecutor1Id: string;
  blockingExecutor2Id: string;
  blockingStatus: CorsetOperationStatus;
  comment: string;
  competentCutting: boolean;
  controlledById: string;
  corsetFastenersInstallation: boolean;
  corsetProblocking: boolean;
  corsetStatus: CorsetStatus;
  cuttingExecutor1Id: string;
  cuttingExecutor2Id: string;
  cuttingStatus: CorsetOperationStatus;
  deformationInsideCorsetLiner: boolean;
  execution3DModelEnd: string;
  execution3DModelStart: string;
  fastenersInstallExecutor1Id: string;
  fastenersInstallExecutor2Id: string;
  fastenersInstallStatus: CorsetOperationStatus;
  generalStatus: ProductStatus;
  isControlled: boolean;
  issuer1Id: string;
  issuer2Id: string;
  is3DModelReady: boolean;
  levelOfAxillaryPelot: boolean;
  model3DExecutor1Id: string;
  model3DExecutor2Id: string;
  otherDefects: string;
  paintQualityAfterBlocking: boolean;
  participationPercent1: number;
  participationPercent2: number;
  plasticBend: boolean;
  price: number;
  productReadinessAtTime: boolean;
  productionTime: OrderTerm;
  purityBeforeLoadingInThermostol: boolean;
  sameColorFrames: boolean;
  seamPolishing: boolean;
  statusComplete: boolean;
  stonesAfterTights: boolean;
  surfaceScratches: boolean;
  turningExecutor1Id: string;
  turningExecutor2Id: string;
  turningQuality: boolean;
  turningStatus: CorsetOperationStatus;
  whriteWhoInstalledFasteners: boolean;
  whriteWhoTurned: boolean;
}
