import { Measurement } from '@common/interfaces/Measurement';
import { MediaFile } from '@common/models/media-file';
import { DealCreate } from '@common/interfaces/Deal-create';
import { CorsetMeasurement } from '@common/interfaces/product-order/Corset-measurement';
import { ProthesisVkMeasurement } from '@common/interfaces/product-order/Prothesis-vk-measurement';
import { CommonFile } from '@common/models/common-file';
import { ApparatLegMeasurement } from '@common/models/product-order/apparatus-order/apparat-leg-measurement';
import {ProthesisNkMeasurement} from '@modules/patients/patient/patient-visits/visit-meansurements/protez-nk-device-measurement/prothesis-nk-measurement';

export interface VisitCreate {
  dateTime?: string;
  dealId?: string;
  dealCreateRequest?: DealCreate;
  medicalServiceId?: string;
  visitReasonId?: string;
  acceptXRay?: boolean;
  roomId?: string;
  contactId?: string;
  appointmentId?: string;
  healingDynamicId?: string;
  disabilityGroupId?: string;
  diagnosis1Id?: string;
  diagnosis2Id?: string;
  iprPrpId?: string;
  mkb10Id?: string;
  growth?: number;
  weight?: number;
  footSize?: number;
  amputationSide?: string;
  complaints?: string;
  comment?: string;
  recommendedCorsetWearing?: string;
  actualCorsetWearing?: string;
  measurements?: Measurement[];
  doctorId?: string;
  dateTimeStart?: string;
  dateTimeEnd?: string;
  anamnesis?: string;
  healingPlan?: string;
  attendantDiagnosis?: string;
  iprPrpActualDate?: Date;
  iprPrpComment?: string;
  stumpVicesVkId?: string;
  photos?: MediaFile[];
  videos?: MediaFile[];
  corsetMeasurement?: CorsetMeasurement;
  prothesisVkMeasurement?: ProthesisVkMeasurement;
  prothesisNkMeasurement?: ProthesisNkMeasurement;
  apparatLegMeasurement?: ApparatLegMeasurement;
  otherFiles?: CommonFile[];
  purchaseId?: string;
  nextVisitDate?: Date;
}
